// Code generated by tfgen. DO NOT EDIT.

variable "allowed_account_id" {
  description = "AWS account identifier this code is permitted to run against."
  type        = string
}

provider "aws" {
  region              = "eu-west-1"
  allowed_account_ids = [var.allowed_account_id]
  default_tags {
    tags = {
      env    = "dev"
      source = "github.com/vorotech/terraform-examples"
    }
  }
}

data "aws_default_tags" "this" {}
